include colors/custom/geto1.conf

font_family     GoogleSans Code NF 
font_size       11

disable_ligatures no
enabl_audio_bell  no 

shell             zsh 
shell_integration disabled


cursor_shape    block

url_style       curly

remember_window_size   no
intial_window_width    73c
intial_window_height   23c
window_padding_width   10
cursor_blink_interval  0

background_opacity             0.8
scrollbar_handle_opacity       0
scrollbar_track_opacity        0
scrollbar_track_hover_opacity  0
confirm_os_window_close        0

# - - Performance settings
sync_to_monitor  no

# - - Perf
repaint_delay    8
input_delay      3

cursor_trail                 30 
cursor_trail_decay           0.1 0.3
cursor_trail_start_threshold 0
